//
// GGMAX 3.83 - Object Library LIVE PREVIEW (DX12)
// ============================================================================
//
// THE REGRESSION
// --------------
// Hovering a thumbnail in the Object Library used to replace the static image with a LIVE
// render of the object, slowly rotating (and playing its idle animation for characters).
// The whole game-side half of that feature survived the DX12 port intact - M-GridEditB_part9.cpp
// diffs 1:1 against DX11 apart from Timer()->MAXTimer() - but the renderer half did not:
// GrabBackBufferCopy() (M-GridEditB_part7.cpp) opens with an unconditional
//
//     if (ImGui_DX12_IsInitialized()) return;
//
// because its DX11 implementation rendered into legacy bitmap 99 and then pulled pixels out
// with GrabImage(). In DX12 `m_pD3D` is NULL (master_part0.cpp:94), so GrabImageCore() bails
// on its first line and the whole DBP image-grab layer is dead. Master::ForceRender's
// SetRenderTarget and ComposeSimple calls are commented out for the same reason.
//
// ★ Same shape as the other five port defects: nothing BROKE. Something MOVED - the pixels
//   now live in a DX12 resource the DX11 image layer cannot see - and nothing told anyone.
//
// WHAT THIS USES INSTEAD
// ----------------------
// Wicked DX12 has a native feature the DX11 fork did not: CameraComponent::render_to_texture.
// Give any scene CameraComponent a non-zero `render_to_texture.resolution` and
// RenderPath3D::RenderCameraComponents (wiRenderPath3D.cpp:2919, called unconditionally from
// Render()) allocates the targets, culls, prepasses, tile-culls the lights, draws opaque +
// transparent + sky and generates a mip chain - every frame, from that camera, into its own
// texture. That is exactly the "manually created backbuffer capture" the DX11 code had to
// hand-roll, now done by the engine.
//
// So this file does only the three things the engine does NOT do:
//   1. owns the scene CameraComponent and drives it from GG camera space,
//   2. tonemaps the engine's HDR result (format_rendertarget_main = R11G11B10_FLOAT) into an
//      LDR texture, because ImGui samples raw and would otherwise show linear HDR,
//   3. hands that LDR texture to the ImGui DX12 bridge so the thumbnail cell can draw it.
//
// ⚠ NO ENGINE CHANGE. Nothing in WickedEngineDX12 is touched, so no WICKED_ENGINE_CHANGES.md
//   delta row is owed and the sweeps see an unchanged engine.
//
// ⚠ COST WHEN IDLE IS ZERO. resolution == {0,0} makes RenderCameraComponents free its
//   resources and `continue` on its first line, and GGObjectPreview_Render() early-outs.
//   The pass only exists while the pointer is actually resting on a thumbnail.
//
// SCOPE
// -----
// This restores the LIVE PREVIEW only. GrabBackBufferCopy's other three customers - thumbnail
// generation to disk (BackBufferSaveCacheName), snapshot mode and the particle-thumb mode -
// still need a GPU->CPU readback that does not exist in DX12 yet, and are left switched off
// exactly as they were. See M-GridEditB_part7.cpp for the gate that says so.
//

// GGMAX 3.83 bisect switch - see SET_OBJPREVIEW in AutomationHarness.cpp.
// 0 off | 1 engine render_to_texture only | 2 + tonemap | 3 + ImGui bind (default)
int gg_objpreview_mode = 3;
// Fixed grading for the preview. <= 0 means 'use the level's exposure', which is what the
// first working build did and why the archway came out near-black at exposure 0.145.
float gg_objpreview_exposure = 1.0f;
// 0 = leave the backdrop plane exactly as GrabBackBufferCopy built it
// 1 = force it opaque and keep its authored texture (default)
// 2 = force it opaque and override the texture with a flat colour
int gg_objpreview_backdrop = 1;
// ★ The preview owns its lighting. A point light's illuminance falls as 1/d^2 and the
// framing distance scales with the object (fCamMove = fLargest * ~3.5, anything from ~50
// to ~8750 units), so a FIXED intensity cannot work across the library - the shipped
// thumb lights are 8 candela with a 2900 range, which is a fraction of a lux on a small
// prop and entirely out of range on a large one. Scale both with the distance instead.
// k is the illuminance the key light lands on the subject: intensity = k * d^2, so the same k
// frames a 15-unit prop and a 2500-unit building identically.
//
// ★ MATCHED TO THE DX11 REFERENCE, and the statistic is the whole story. The shipped static
// thumbnails were generated by DX11, so one of them sitting in the same grid IS the reference -
// but comparing on MEAN cell luminance says a correct preview and a blown one are identical
// (66.8 vs 67.6 on Lee's two screenshots), because the backdrop plane fills most of the cell and
// swamps the subject. p99 - the brightest 1%, which is the lit side of the subject - told the
// truth: 145.6 reference against 220.1 live.
//
// Measured in-session against the static thumbnail in the same cell at the same resolution
// (tools/objpreview_match_dx11.sh), reference p99 150.3:
//     k = 0.00008 -> 132.5     k = 0.00025 -> 183.1     k = 0.00060 -> 223.9
//     k = 0.00015 -> 155.4     k = 0.00040 -> 208.2
// 0.00013 interpolates onto the reference.
//
// ⚠ The response saturates HARD at the top: above k ~0.01 every value is pixel-identical, so a
// sweep that starts too high reads as a dead knob. It cost a whole run reading a flat line as
// 'the override is not being applied'.
//
// ⚠⚠⚠ SUPERSEDED 3.97 - THE k*d^2 MODEL WAS WRONG FOR THIS ENGINE, AND IT TURNED A BUILDING WHITE.
// It assumed a point light falls off as 1/d^2. This fork does not: 2.10 put the DX11 falloff
// back, energy * (1 - d^2/r^2)^2 with NO inverse-square term (lightingHF.hlsli
// attenuation_pointlight, OPTION_BIT_GG_DX11_LIGHT_FALLOFF). With the range scaled to 6d the window
// term is ~0.92 at every size, so the light a subject receives IS the intensity - and k*d^2 made
// it grow with the square of the object's size. A building framed at d = 1677 got 365 units and
// every face saturated; a small prop at d = 60 got 0.47. One object calibrated, the rest of the
// library wrong in both directions. ★ A calibration is only as general as the physics it
// assumes - check the falloff before fitting a constant to a single object.
//
// Now: a FIXED intensity (the window term does the only distance work there is to do). lightk is
// kept as an experiment knob - >0 brings the old k*d^2 back.
float gg_objpreview_lightk = 0.0f;     // >0 = old k*d^2 model (experiments only)
float gg_objpreview_lightint = 4.0f;   // key light energy, DX11 units; fill is 0.45 of this

// ★★★ 3.97 THE PREVIEW OWNS ITS WHOLE ENVIRONMENT, NOT JUST ITS LIGHTS.
// The preview camera used to draw with the level's frame constants: the level's ambient, its sun,
// its fog, its global probe, its local probes. Lee's rebuilt testpro2level carries an ambient of
// 0.608 where the 3.84 calibration level had 0, so the same library item changed brightness with
// the level loaded behind it. A thumbnail is a product shot: it should look the same everywhere.
// GGObjectPreview_FrameOverride (below) hands the preview camera its own copy of the frame
// constants through the engine's gg_rtt_frame_override hook, with every level input replaced by
// a fixed studio value. 0 = inherit the level exactly as before (A/B only).
int gg_objpreview_studio = 1;
// Flat ambient added on top of the studio cube's own (weather.ambient replacement), linear.
float gg_objpreview_ambient = 0.0f;
// Brightness of the generated studio sky cube, which feeds BOTH the ambient (its 1x1 mip, per
// face) and the reflections metals depend on. Rebuilt on change - it is 32x32 per face.
float gg_objpreview_envscale = 0.35f;
// 3.97b ONE brightness modulation for the whole rig - key, fill and the studio cube together -
// so parity with the DX11 thumbnails is a single number rather than three that drift apart.
// The three values above are the rig's SHAPE; this is its level.
float gg_objpreview_modulate = 1.0f;
// Harness-only: hold the turntable at the hover's starting angle (see M-GridEditB_part7.cpp).
int gg_objpreview_freeze = 0;

// ★★★ 3.98 THE LIGHTING STAGE. Four lights placed around the SUBJECT in the CAMERA's frame, so
// as the turntable spins each face passes through key, fill and rim in turn instead of meeting
// one flat front light. Per light: azimuth (deg, 0 = at the camera, +90 = camera right,
// 180 = behind the subject), elevation (deg above the horizontal), and strength as a
// multiple of gg_objpreview_lightint * gg_objpreview_modulate. Strength 0 = light off.
// Distance is the camera's own distance, so the stage scales with the object like the framing.
float gg_objpreview_stage[4][3] = {
	{  45.0f, 50.0f, 1.00f },	// KEY  - high and to the right: lights tops and interiors (the ammo box)
	{ -60.0f, 15.0f, 0.35f },	// FILL - low on the other side, keeps the shadow side readable
	{ 150.0f, 45.0f, 0.90f },	// RIM  - behind and above: separates the silhouette from the backdrop
	{   0.0f,-40.0f, 0.00f },	// BOUNCE - from below the camera, off by default
};
// Softboxes in the studio sky, as a multiple of their built-in strength. A glossy surface shows
// what it REFLECTS; with only a smooth grey gradient to reflect, the pistol-ammo box read as
// lacklustre. 0 = the plain gradient of 3.97.
float gg_objpreview_softbox = 1.0f;
// 3.98 diagnostic, harness-only: one-shot mesh repair on the parked preview object (see Submit).
int gg_objpreview_meshfix = 0;
// Framing. DX11 rendered the thumbnail with the EDITOR's fixed 45 (-> PI/3 vertical), not
// the level's camera FOV, and every distance constant in GrabBackBufferCopy was fitted to
// that. Passing the level's FOV made every object 1.39x too large.
float gg_objpreview_fovdeg = 45.0f;
// Material overrides applied to the PREVIEW OBJECT ONLY (a temporary bank object, never a
// placed instance). <0 = leave the material as loaded.
float gg_objpreview_metal = -1.0f;
float gg_objpreview_rough = -1.0f;
// Bounce fill strength as a fraction of the key, 0 disables the third light.
// ⚠ DEFAULT OFF. The rig is here and works, but the shipped calibration (lightk) was matched
// to the DX11 reference thumbnails WITHOUT it, and switching it on shifts that match. It was
// added chasing the black-torso zombie and did not fix it (torso mean 26.9 -> 27.6), so there
// is no evidence to pay for the recalibration yet. SET_OBJPREVIEW_MAT's third argument turns
// it on for experiments.
float gg_objpreview_bounce = 0.0f;
// Diagnostic: 1 forces the preview object's materials UNLIT (baseColor * texture, no
// lighting term). Splits 'the lighting is wrong' from 'the texture sample is black'.
int gg_objpreview_unlit = 0;

// 3.97: the engine's per-camera frame-constant hook (wiRenderPath3D.cpp).
namespace wi { extern bool (*gg_rtt_frame_override)(wi::ecs::Entity cameraEntity, const FrameCB& src, FrameCB& dst); }

namespace GGObjectPreview
{
	static wi::ecs::Entity			s_camEntity = 0;		// scene CameraComponent that does the render
	static wi::graphics::Texture	s_ldr;					// tonemapped copy, what ImGui samples
	static int						s_ldrW = 0, s_ldrH = 0;
	static int						s_reqW = 0, s_reqH = 0;	// requested preview size (BackBufferSizeX/Y)
	static int						s_imageId = 0;			// GG image id this live render stands in for
	static bool						s_active = false;		// a preview is requested
	static bool						s_haveFrame = false;	// at least one tonemapped frame exists
	static void*					s_imTexId = nullptr;	// ImGui texture id for s_ldr
	static int						s_parkedObject = 0;		// GG object currently parked in preview space
	static float					s_parkedPos[3] = { 0,0,0 };
	static float					s_parkedAng[3] = { 0,0,0 };
	static bool						s_parkedVisible = false;
	static int						s_backdropObject = 0;	// backdrop plane held visible for the preview
	static int						s_litLights = 0;		// lights forced into the MAIN visibility this frame
	static int						s_evictions = 0;		// times a predecessor had to be un-parked
	static wi::ecs::Entity			s_bounceLight = 0;		// module-owned bounce fill from below-front
	static wi::ecs::Entity			s_rimLight = 0;			// 3.98 module-owned rim light

	// ★ The engine's own framing reference. DX11 rendered the thumbnail at a FIXED 1920x1017
	// (Master::ForceRender's USEFIXEDBACKBUFFERSIZE viewport / MakeBitmap(99,1920,1017)) and
	// then GrabImage'd the centre BackBufferSizeX x BackBufferSizeY out of it. All of
	// GrabBackBufferCopy's camera-distance tuning - fAdjustRange, fCamMove, the fLargestY
	// ladder - was fitted against that crop, so to reuse that maths unchanged the preview
	// camera has to reproduce the crop's field of view rather than the full frame's.
	static const float FRAMING_REFERENCE_HEIGHT = 1017.0f;

	// ★ The preview camera owns its clip range rather than borrowing the level's.
	// GrabBackBufferCopy parks the backdrop plane 21200 units out (MoveObject -21200), so a
	// level whose far plane is nearer than that renders the preview on black - which is
	// every indoor level. Reverse-Z keeps the precision near the eye, so a far plane wide
	// enough for the backdrop costs nothing.
	static const float PREVIEW_ZNEAR = 1.0f;
	static const float PREVIEW_ZFAR = 60000.0f;

	// The flat stand-in for the DX11 backdrop image, used only when the plane has no
	// base-colour texture. Picked to sit where the shipped library thumbnails sit: a
	// desaturated blue that a grey or brown object reads clearly against.
	static const float PREVIEW_BACKDROP_R = 0.106f;
	static const float PREVIEW_BACKDROP_G = 0.208f;
	static const float PREVIEW_BACKDROP_B = 0.361f;
	static int s_backdropDiag = 0;   // 0 untested, 1 had a texture, 2 flat colour applied

	// 3.97 the studio sky cube. Tiny and generated, NOT a skybank cube: those are 32 MB of BC6H
	// each, and a thumbnail is not worth 32 MB of a 4 GB budget with ~300 MB of headroom.
	static wi::graphics::Texture s_studioCube;
	static int s_studioCubeIndex = -1;		// bindless SRV index, -1 = not built
	static float s_studioCubeBuiltScale = -1.0f;
	static int s_studioFrames = 0;			// frames the override has actually been applied (diagnostic)
}

// Is a live preview currently being driven? (used by the image-id override and by the
// GrabBackBufferCopy teardown path)
bool GGObjectPreview_IsActive(void)
{
	return GGObjectPreview::s_active;
}

static void GGObjectPreview_RestoreParked(void);

// Remember where a GG object was before we parked it in preview space, so the un-hover path
// can put it back. DX11 restored it on the same call because it rendered synchronously inside
// GrabBackBufferCopy; we cannot, because the engine renders the preview camera in the NEXT
// frame's Render() - the object has to still be there when it does.
void GGObjectPreview_ParkObject(int ggObject, float px, float py, float pz, float ax, float ay, float az, bool bWasVisible)
{
	using namespace GGObjectPreview;
	if (s_parkedObject == ggObject) return;		// already parked, keep the ORIGINAL transform
	// ★ DEFECT 4. Adopting a new object without giving the previous one back left it sitting
	// at the park point, and the preview camera then rendered BOTH - Lee's "two objects
	// superimposed". Moving from thumbnail A to thumbnail B never passes through Stop(),
	// because a preview is still active the whole time.
	if (s_parkedObject > 0) { GGObjectPreview_RestoreParked(); s_evictions++; }
	s_parkedObject = ggObject;
	s_parkedPos[0] = px; s_parkedPos[1] = py; s_parkedPos[2] = pz;
	s_parkedAng[0] = ax; s_parkedAng[1] = ay; s_parkedAng[2] = az;
	s_parkedVisible = bWasVisible;
}

// The backdrop plane GrabBackBufferCopy positioned for this preview. It stays visible for
// as long as the preview runs, because the render happens a frame after the setup.
void GGObjectPreview_HoldBackdrop(int backdropObject)
{
	using namespace GGObjectPreview;
	const bool bNew = (s_backdropObject != backdropObject);
	s_backdropObject = backdropObject;
	if (!bNew || backdropObject <= 0 || ObjectExist(backdropObject) != 1) return;

	// Does the plane actually carry its backdrop image in DX12? TextureObject() feeds the
	// legacy DBP image layer, which the DX12 port no longer wires into Wicked materials.
	sObject* pBack = GetObjectData(backdropObject);
	if (!pBack || !pBack->ppMeshList || pBack->iMeshCount <= 0) return;
	sMesh* pMesh = pBack->ppMeshList[0];
	if (!pMesh) return;
	wi::scene::MeshComponent* mesh = wi::scene::GetScene().meshes.GetComponent(pMesh->wickedmeshindex);
	if (!mesh || mesh->subsets.empty()) return;
	wi::scene::MaterialComponent* mat = wi::scene::GetScene().materials.GetComponent(mesh->subsets[0].materialID);
	if (!mat) return;

	if (gg_objpreview_backdrop == 0) { s_backdropDiag = 3; return; }

	const bool bHasTexture = mat->textures[wi::scene::MaterialComponent::BASECOLORMAP].resource.IsValid();

	// ⚠ This is the whole bug. CreateBackdropObject does SetObjectTransparency(obj, 1), so
	// the material carries FILTER_TRANSPARENT and GetBlendMode() returns BLENDMODE_ALPHA
	// regardless of userBlendMode - and the backdrop images have no usable alpha, so a
	// perfectly resident texture blended away to nothing and the preview sat on black.
	mat->shaderType = wi::scene::MaterialComponent::SHADERTYPE_UNLIT;
	mat->userBlendMode = wi::enums::BLENDMODE_OPAQUE;
	mat->SetAlphaRef(1.0f);

	if (bHasTexture && gg_objpreview_backdrop == 1)
	{
		// keep what the object's fpe asked for; white base colour so the image comes through
		mat->SetBaseColor(XMFLOAT4(1.0f, 1.0f, 1.0f, 1.0f));
		s_backdropDiag = 1;
	}
	else
	{
		mat->SetBaseColor(XMFLOAT4(PREVIEW_BACKDROP_R, PREVIEW_BACKDROP_G, PREVIEW_BACKDROP_B, 1.0f));
		s_backdropDiag = 2;
	}
	mat->SetDirty(true);
}

// Give the parked object back. Split out of Stop() because the A->B hover switch has to do
// exactly this and nothing else - it must NOT tear the pass down, a preview is still running.
static void GGObjectPreview_RestoreParked(void)
{
	using namespace GGObjectPreview;
	if (s_parkedObject <= 0) return;
	if (ObjectExist(s_parkedObject) == 1)
	{
		PositionObject(s_parkedObject, s_parkedPos[0], s_parkedPos[1], s_parkedPos[2]);
		RotateObject(s_parkedObject, s_parkedAng[0], s_parkedAng[1], s_parkedAng[2]);
		if (s_parkedVisible) ShowObject(s_parkedObject); else HideObject(s_parkedObject);
	}
	s_parkedObject = 0;
}

// Put the parked object back and stop the pass. Safe to call every frame.
void GGObjectPreview_Stop(void)
{
	using namespace GGObjectPreview;
	GGObjectPreview_RestoreParked();
	if (s_backdropObject > 0)
	{
		if (ObjectExist(s_backdropObject) == 1) HideObject(s_backdropObject);
		s_backdropObject = 0;
	}
	// ⚠ Unconditional. Nested inside the backdrop branch, a preview that never got a backdrop
	// left both lights - and the light-shaft / lens-flare switches they turn off, which are
	// GLOBAL RenderPath3D state - stuck for the rest of the session.
	WickedCall_EnableThumbLight(false);
	if (s_bounceLight != 0)
	{
		wi::scene::GetScene().Entity_Remove(s_bounceLight);
		s_bounceLight = 0;
	}
	if (s_rimLight != 0)
	{
		wi::scene::GetScene().Entity_Remove(s_rimLight);
		s_rimLight = 0;
	}
	if (s_camEntity != 0)
	{
		wi::scene::CameraComponent* cam = wi::scene::GetScene().cameras.GetComponent(s_camEntity);
		if (cam)
		{
			// resolution 0 makes RenderCameraComponents drop the whole render_to_texture block
			// (targets, depth, tile buffer, visibility) on its next pass - see its first lines.
			cam->render_to_texture.resolution = XMUINT2(0, 0);
		}
	}
	s_active = false;
	s_haveFrame = false;
	s_imageId = 0;
}

// ★★★ THE FIX FOR DEFECTS 1 AND 2.
//
// Runs between Scene::Update (which rebuilds scene.aabb_lights) and RenderPath3D::PreRender
// (whose UpdateVisibility reads them) - the same slot, and for the same reason, as the
// WickedCall_UpdateCharacterShadows call it sits next to in Master::Update.
//
// UpdateVisibility keeps a light only if its cull AABB passes the MAIN camera's frustum
// (wiRenderer.cpp:4683), and ONLY the lights that survive that test are packed into the frame's
// shader entity array (wiRenderPath3D.cpp:473 -> wiRenderer.cpp:6349). The preview's lights live
// 39000 units above the editor camera, so they were always culled and therefore invisible to
// every camera - including the preview's own, whose tiled culling can only reference entities
// that are already in that one shared array.
//
// ⚠ So the per-camera visLight count is NOT a count of lights the shader can see. It reported 2
//   the whole time the object was rendering pure black.
//
// Giving them an infinite AABB costs two entity slots and nothing else: they are 39000 units up
// with a range that reaches only the preview, so they illuminate nothing in the level.
void GGObjectPreview_PreVisibility(void)
{
	using namespace GGObjectPreview;
	if (!s_active) return;
	extern wi::ecs::Entity g_entityThumbLight, g_entityThumbLight2;
	wi::scene::Scene& scene = wi::scene::GetScene();
	const wi::ecs::Entity le[4] = { g_entityThumbLight, g_entityThumbLight2, s_bounceLight, s_rimLight };
	s_litLights = 0;
	for (int i = 0; i < 4; ++i)
	{
		if (!le[i]) continue;
		const size_t idx = scene.lights.GetIndex(le[i]);
		if (idx == ~0ull || idx >= scene.aabb_lights.size()) continue;
		wi::primitive::AABB& box = scene.aabb_lights[idx];
		box._min = XMFLOAT3(-FLT_MAX, -FLT_MAX, -FLT_MAX);
		box._max = XMFLOAT3(FLT_MAX, FLT_MAX, FLT_MAX);
		box.layerMask = ~0u;
		s_litLights++;
	}
}

// ============================================================================ 3.97 STUDIO
// The radiance of the studio 'sky', by direction: a bright soft top, a mid horizon, a dark
// floor. Neutral grey on purpose - the backdrop already supplies the blue, and a tinted sky
// would tint every thumbnail in the library.
static void GGObjectPreview_StudioRadiance(float x, float y, float z, float out[3])
{
	const float len = sqrtf(x*x + y*y + z*z);
	const float t = (len > 0.0f) ? (y / len) : 0.0f;
	const float top = 1.0f, horizon = 0.55f, floorv = 0.18f;
	float v;
	if (t >= 0.0f) v = horizon + (top - horizon) * powf(t, 0.6f);
	else           v = horizon + (floorv - horizon) * powf(-t, 0.5f);
	// 3.98 softboxes. The preview camera always looks along +Z (GrabBackBufferCopy frames it with
	// RotateCamera(0,0,0) then MoveCamera back), so a world-fixed cube is camera-fixed in effect:
	// -Z is BEHIND the camera, which is what camera-facing surfaces reflect.
	if (gg_objpreview_softbox > 0.0f && len > 0.0f)
	{
		const float nx = x / len, ny = y / len, nz = z / len;
		static const float box[3][4] = {
			{  0.55f, 0.65f, -0.52f, 2.5f },	// key side, upper right behind the camera
			{ -0.75f, 0.35f, -0.55f, 1.0f },	// fill side, left
			{  0.00f, 1.00f,  0.25f, 1.8f },	// overhead
		};
		for (int b = 0; b < 3; ++b)
		{
			const float bl = sqrtf(box[b][0]*box[b][0] + box[b][1]*box[b][1] + box[b][2]*box[b][2]);
			const float c = (nx*box[b][0] + ny*box[b][1] + nz*box[b][2]) / bl;
			if (c > 0.0f) v += box[b][3] * gg_objpreview_softbox * powf(c, 12.0f);
		}
	}
	v *= gg_objpreview_envscale * gg_objpreview_modulate;
	out[0] = v; out[1] = v; out[2] = v;
}

// Build (or rebuild) the studio cube. MAIN THREAD ONLY - called from Submit, which runs inside
// GrabBackBufferCopy on the game loop, per the resource-creation rule.
static void GGObjectPreview_EnsureStudioCube(void)
{
	using namespace GGObjectPreview;
	static float s_builtSoftbox = -1.0f;
	if (s_studioCube.IsValid() && s_studioCubeBuiltScale == gg_objpreview_envscale * gg_objpreview_modulate
		&& s_builtSoftbox == gg_objpreview_softbox) return;
	s_builtSoftbox = gg_objpreview_softbox;
	wi::graphics::GraphicsDevice* device = wi::graphics::GetDevice();
	if (!device) return;
	const int N = 32, MIPS = 6;			// 32,16,8,4,2,1 - the 1x1 is what GetAmbient reads
	// mip 0 evaluated per texel, then each mip a 2x2 box of the one above, so the 1x1 is the
	// face AVERAGE (a true ambient) rather than whatever sits at the face centre.
	static std::vector<float> texels[6][6];
	for (int f = 0; f < 6; ++f)
	{
		texels[f][0].assign((size_t)N * N * 4, 1.0f);
		for (int y = 0; y < N; ++y)
		for (int x = 0; x < N; ++x)
		{
			const float u = 2.0f * (x + 0.5f) / N - 1.0f;
			const float v = 2.0f * (y + 0.5f) / N - 1.0f;
			float d[3];
			switch (f)	// D3D cube face order +X -X +Y -Y +Z -Z
			{
			case 0: d[0] =  1; d[1] = -v; d[2] = -u; break;
			case 1: d[0] = -1; d[1] = -v; d[2] =  u; break;
			case 2: d[0] =  u; d[1] =  1; d[2] =  v; break;
			case 3: d[0] =  u; d[1] = -1; d[2] = -v; break;
			case 4: d[0] =  u; d[1] = -v; d[2] =  1; break;
			default: d[0] = -u; d[1] = -v; d[2] = -1; break;
			}
			float c[3];
			GGObjectPreview_StudioRadiance(d[0], d[1], d[2], c);
			float* p = &texels[f][0][((size_t)y * N + x) * 4];
			p[0] = c[0]; p[1] = c[1]; p[2] = c[2]; p[3] = 1.0f;
		}
		for (int m = 1; m < MIPS; ++m)
		{
			const int S = N >> m, P2 = N >> (m - 1);
			texels[f][m].assign((size_t)S * S * 4, 1.0f);
			const std::vector<float>& a = texels[f][m - 1];
			for (int y = 0; y < S; ++y)
			for (int x = 0; x < S; ++x)
			for (int ch = 0; ch < 4; ++ch)
			{
				const float sum = a[((size_t)(2*y) * P2 + 2*x) * 4 + ch] + a[((size_t)(2*y) * P2 + 2*x + 1) * 4 + ch]
				              + a[((size_t)(2*y + 1) * P2 + 2*x) * 4 + ch] + a[((size_t)(2*y + 1) * P2 + 2*x + 1) * 4 + ch];
				texels[f][m][((size_t)y * S + x) * 4 + ch] = sum * 0.25f;
			}
		}
	}
	wi::graphics::SubresourceData init[6 * 6];
	for (int f = 0; f < 6; ++f)
	for (int m = 0; m < MIPS; ++m)
	{
		const int S = N >> m;
		wi::graphics::SubresourceData& sd = init[f * MIPS + m];	// D3D12 subresource = mip + slice * mips
		sd.data_ptr = texels[f][m].data();
		sd.row_pitch = (uint32_t)(S * 4 * sizeof(float));
		sd.slice_pitch = (uint32_t)(S * S * 4 * sizeof(float));
	}
	wi::graphics::TextureDesc desc;
	desc.type = wi::graphics::TextureDesc::Type::TEXTURE_2D;
	desc.width = N; desc.height = N; desc.array_size = 6; desc.mip_levels = MIPS;
	desc.format = wi::graphics::Format::R32G32B32A32_FLOAT;
	desc.bind_flags = wi::graphics::BindFlag::SHADER_RESOURCE;
	desc.misc_flags = wi::graphics::ResourceMiscFlag::TEXTURECUBE;
	desc.layout = wi::graphics::ResourceState::SHADER_RESOURCE;
	wi::graphics::Texture cube;
	if (!device->CreateTexture(&desc, init, &cube)) return;
	device->SetName(&cube, "GGMax ObjectPreview StudioCube");
	s_studioCube = cube;		// the old one (if any) is released by the device's deferred destroy
	s_studioCubeIndex = device->GetDescriptorIndex(&s_studioCube, wi::graphics::SubresourceType::SRV);
	s_studioCubeBuiltScale = gg_objpreview_envscale * gg_objpreview_modulate;
}

// The engine calls this from the preview camera's render job with a copy of this frame's
// constants (wiRenderPath3D.cpp, gg_rtt_frame_override). Every value below would otherwise come
// from the LEVEL. ⚠ dst is write-combined upload memory: read src, only WRITE dst.
// ⚠ Job thread: touches nothing but plain module state that the main thread sets.
static bool GGObjectPreview_FrameOverride(wi::ecs::Entity cameraEntity, const FrameCB& src, FrameCB& dst)
{
	using namespace GGObjectPreview;
	if (!gg_objpreview_studio || !s_active || cameraEntity != s_camEntity) return false;

	// the level's sun, and any other directional light, lights everything at any distance
	dst.directional_lights = 0;
	// local env probes - none can reach y=39000, but the list is emptied rather than trusted
	dst.probes = 0;
	// the global probe is a capture of the LEVEL (sky or interior); swap in the studio cube
	dst.scene.globalprobe = s_studioCubeIndex;
	dst.scene.gg_envprobe_brightness = 1.0f;
	dst.scene.gg_probeonlyglobal = 1;
	dst.scene.ddgi.probe_buffer = -1;
	// flat ambient: THE value that turned the building white (0.608 in testpro2level)
	dst.scene.weather.ambient = wi::math::pack_half3(gg_objpreview_ambient, gg_objpreview_ambient, gg_objpreview_ambient);
	dst.scene.weather.sun_color = wi::math::pack_half3(0.0f, 0.0f, 0.0f);
	// fog: off three ways, because the two fog paths read different fields (fogHF.hlsli) -
	// and the BACKDROP is 21200 units out, so a level's fog was greying the background too
	dst.scene.weather.fog.density = 0.0f;
	dst.scene.weather.fog.start = 1.0e9f;
	dst.scene.weather.gg_fog_opacity = 0.0f;
	dst.texture_volumetricclouds_shadow_index = -1;
	dst.options = src.options & ~(uint32_t)(OPTION_BIT_HEIGHT_FOG | OPTION_BIT_VXGI_ENABLED
		| OPTION_BIT_VXGI_REFLECTIONS_ENABLED | OPTION_BIT_SURFELGI_ENABLED | OPTION_BIT_RAYTRACED_SHADOWS
		| OPTION_BIT_SHADOW_MASK | OPTION_BIT_DISABLE_ALBEDO_MAPS | OPTION_BIT_FORCE_DIFFUSE_LIGHTING
		| OPTION_BIT_VOLUMETRICCLOUDS_CAST_SHADOW);
	s_studioFrames++;
	return true;
}
// Called once per frame from GrabBackBufferCopy with the camera GG's own framing maths worked
// out. Position/angles are GG camera space, which maps 1:1 onto Wicked world space through the
// same TransformComponent recipe master_part0.cpp:531 uses for the editor camera.
void GGObjectPreview_Submit(int imageId, int width, int height,
	float camX, float camY, float camZ,
	float angX, float angY, float angZ,
	float fovYFullFrame, float zNear, float zFar)
{
	using namespace GGObjectPreview;

	if (gg_objpreview_mode <= 0) return;
	if (imageId <= 0 || width <= 0 || height <= 0) return;

	// A NaN projection is a GPU hang, not a wrong picture: XM_PI/(CameraFOV_f/15) goes
	// infinite at CameraFOV_f == 15 and negative below it, and a zero near plane divides
	// by zero in the reverse-Z matrix. Neither is reachable through the UI - but neither
	// was ever checked here, and this camera is built from level data.
	// ★ DEFECT 3. The caller passes the LEVEL's camera FOV; DX11 rendered the thumbnail with
	// the EDITOR's fixed 45 (M-GridEditB_part3.cpp:213 sets fUsedFOV = 45 whenever
	// bImGuiInTestGame is false), and every distance constant in GrabBackBufferCopy was
	// fitted against that. Using the level's made the object 1.39x too large.
	(void)fovYFullFrame;
	fovYFullFrame = XM_PI / (gg_objpreview_fovdeg / 15.0f);
	if (!(fovYFullFrame > 0.05f) || fovYFullFrame > 2.8f) fovYFullFrame = 1.0471976f; // 60 deg
	// zNear/zFar arrive from the level and are deliberately ignored - see PREVIEW_ZFAR.
	(void)zNear; (void)zFar;
	zNear = GGObjectPreview::PREVIEW_ZNEAR;
	zFar = GGObjectPreview::PREVIEW_ZFAR;

	// clamp - a runaway BackBufferSizeX would allocate a very large set of engine targets
	if (width > 2048) width = 2048;
	if (height > 2048) height = 2048;

	wi::scene::Scene& scene = wi::scene::GetScene();

	// 3.97: the studio environment. The hook is a plain pointer the engine checks per camera, so
	// registering it every submit costs nothing and survives anything that might reset it.
	wi::gg_rtt_frame_override = GGObjectPreview_FrameOverride;
	if (gg_objpreview_studio) GGObjectPreview_EnsureStudioCube();

	// (re)create the camera entity. Checked EVERY submit, not just once: a level load clears
	// the scene and the entity goes with it, and a stale handle would silently render nothing.
	if (s_camEntity == 0 || scene.cameras.GetComponent(s_camEntity) == nullptr)
	{
		s_camEntity = wi::ecs::CreateEntity();
		scene.cameras.Create(s_camEntity);
		// deliberately NO NameComponent and NO TransformComponent:
		//  - a name would show up in anything that walks the scene by name,
		//  - a transform would make Scene::RunCameraUpdateSystem overwrite Eye/At/Up from it
		//    every frame (wiScene.cpp:5843), throwing away what we set below.
	}

	wi::scene::CameraComponent* cam = scene.cameras.GetComponent(s_camEntity);
	if (!cam) return;

	// ---- projection -------------------------------------------------------------------
	// Reproduce the DX11 centre-crop's field of view (see FRAMING_REFERENCE_HEIGHT above) so
	// GrabBackBufferCopy's distance tuning still frames the object the way it always did.
	float tanHalfFull = tanf(fovYFullFrame * 0.5f);
	float tanHalfCrop = tanHalfFull * ((float)height / GGObjectPreview::FRAMING_REFERENCE_HEIGHT);
	if (tanHalfCrop < 0.001f) tanHalfCrop = 0.001f;
	float fovYCrop = 2.0f * atanf(tanHalfCrop);
	cam->CreatePerspective((float)width, (float)height, zNear, zFar, fovYCrop);

	// ---- view -------------------------------------------------------------------------
	// Same recipe as the editor camera so GG angles mean here what they mean everywhere else.
	const double dDegToRad = 3.141592654 / 180.0;
	wi::scene::TransformComponent camera_transform;
	camera_transform.ClearTransform();
	camera_transform.Translate(XMFLOAT3(camX, camY, camZ));
	camera_transform.RotateRollPitchYaw(XMFLOAT3((float)(angX * dDegToRad), (float)(angY * dDegToRad), (float)(angZ * dDegToRad)));
	camera_transform.UpdateTransform();
	cam->TransformCamera(camera_transform);
	cam->jitter = XMFLOAT2(0, 0);		// TAA jitter would make a still preview shimmer

	// ⚠ A CameraComponent's scissor defaults to all zeros, and the shader camera derives
	// scissor_uv from it (wiRenderer.cpp:13324). Any postprocess that opens with
	// is_uv_inside_scissor - the tonemap does, on its first line - would then reject every
	// thread and leave the preview black. RenderCameraComponents sets the VIEWPORT but not
	// this, because nothing it calls reads it.
	cam->canvas.init((uint32_t)width, (uint32_t)height);
	cam->scissor.left = 0;
	cam->scissor.top = 0;
	cam->scissor.right = width;
	cam->scissor.bottom = height;
	cam->sample_count = 1;
	cam->UpdateCamera();

	// ---- ask the engine for the render -------------------------------------------------
	cam->render_to_texture.resolution = XMUINT2((uint32_t)width, (uint32_t)height);
	cam->render_to_texture.sample_count = 1;

	// ★★★ 3.98 THE LIGHTING STAGE. Re-applied EVERY submit: WickedCall_EnableThumbLight destroys
	// and recreates the two thumb lights on every hover, so anything set once is thrown away.
	//
	// 3.84-3.97 put a key almost ON the camera axis (0.45d right, 0.35d up) - every face the camera
	// could see was lit nearly head-on, so a turning object never changed its shading, and anything
	// facing UP (the cartridges inside the pistol-ammo box) got almost nothing. Lights now sit on a
	// sphere around the SUBJECT, placed in the camera's own frame (gg_objpreview_stage), so the
	// stage stays put while the turntable carries each face through it.
	{
		extern wi::ecs::Entity g_entityThumbLight, g_entityThumbLight2;
		extern float BackBufferCamMove;
		float d = BackBufferCamMove * 0.5f;
		if (!(d > 1.0f)) d = 60.0f;
		const float cpitch = cosf((float)(angX * dDegToRad)), spitch = sinf((float)(angX * dDegToRad));
		const float cyaw = cosf((float)(angY * dDegToRad)), syaw = sinf((float)(angY * dDegToRad));
		// left-handed forward for GG's RotateRollPitchYaw(pitch, yaw, roll)
		const float fwdx = cpitch * syaw, fwdy = -spitch, fwdz = cpitch * cyaw;
		// The subject: on the view ray at the camera's distance to the parked object, which is where
		// GrabBackBufferCopy pointed the camera. d is only the fallback.
		float dcam = d;
		if (s_parkedObject > 0 && ObjectExist(s_parkedObject) == 1)
		{
			const float ox = ObjectPositionX(s_parkedObject) - camX;
			const float oy = ObjectPositionY(s_parkedObject) - camY;
			const float oz = ObjectPositionZ(s_parkedObject) - camZ;
			const float od = sqrtf(ox*ox + oy*oy + oz*oz);
			if (od > 1.0f) dcam = od;
		}
		const float tx = camX + fwdx * dcam, ty = camY + fwdy * dcam, tz = camZ + fwdz * dcam;
		// camera frame in the ground plane: b = subject -> camera, r = camera right (LH: up x forward)
		float bx = -fwdx, bz = -fwdz;
		const float bl = sqrtf(bx*bx + bz*bz);
		if (bl > 0.001f) { bx /= bl; bz /= bl; } else { bx = 0.0f; bz = -1.0f; }
		const float rx = -bz, rz = bx;
		// 3.97: FIXED energy - see gg_objpreview_lightint for why k*d^2 was wrong here.
		const float intensity = (gg_objpreview_lightk > 0.0f)
			? gg_objpreview_lightk * d * d
			: gg_objpreview_lightint * gg_objpreview_modulate;
		// module-owned lights exist only while their strength is non-zero
		wi::ecs::Entity* owned[2] = { &s_rimLight, &s_bounceLight };
		const float ownedMul[2] = { gg_objpreview_stage[2][2], gg_objpreview_stage[3][2] };
		for (int k = 0; k < 2; ++k)
		{
			if (ownedMul[k] > 0.0f && *owned[k] == 0)
			{
				*owned[k] = wi::ecs::CreateEntity();
				scene.lights.Create(*owned[k]);
				scene.transforms.Create(*owned[k]);
			}
			else if (ownedMul[k] <= 0.0f && *owned[k] != 0)
			{
				scene.Entity_Remove(*owned[k]);
				*owned[k] = 0;
			}
		}
		const wi::ecs::Entity rig[4] = { g_entityThumbLight, g_entityThumbLight2, s_rimLight, s_bounceLight };
		for (int i = 0; i < 4; ++i)
		{
			if (!rig[i]) continue;
			const float az = gg_objpreview_stage[i][0] * (float)dDegToRad;
			const float el = gg_objpreview_stage[i][1] * (float)dDegToRad;
			const float ce = cosf(el);
			const float lx = (bx * cosf(az) + rx * sinf(az)) * ce;
			const float ly = sinf(el);
			const float lz = (bz * cosf(az) + rz * sinf(az)) * ce;
			wi::scene::LightComponent* lc = scene.lights.GetComponent(rig[i]);
			if (lc)
			{
				lc->type = wi::scene::LightComponent::POINT;
				lc->color = XMFLOAT3(1.0f, 0.98f, 0.95f);
				lc->intensity = intensity * gg_objpreview_stage[i][2];
				// DX11 falloff: (1 - D^2/r^2)^2. r = 3D gives 0.79 at the subject centre at EVERY scale,
				// with a gentle near-to-far fall across the object itself.
				lc->range = dcam * 3.0f;
				lc->SetCastShadow(false);
			}
			wi::scene::TransformComponent* lt = scene.transforms.GetComponent(rig[i]);
			if (lt)
			{
				lt->ClearTransform();
				lt->Translate(XMFLOAT3(tx + lx * dcam, ty + ly * dcam, tz + lz * dcam));
				lt->SetDirty();
			}
		}
	}
	// 3.98 diagnostic: rebuild the parked object's GPU mesh data once (gg_objpreview_meshfix).
	if (gg_objpreview_meshfix > 0 && s_parkedObject > 0 && ObjectExist(s_parkedObject) == 1)
	{
		sObject* pO = GetObjectData(s_parkedObject);
		if (pO && pO->ppMeshList)
		{
			for (int m = 0; m < pO->iMeshCount; ++m)
			{
				sMesh* pM = pO->ppMeshList[m];
				if (!pM) continue;
				wi::scene::MeshComponent* me = scene.meshes.GetComponent(pM->wickedmeshindex);
				if (!me) continue;
				if (gg_objpreview_meshfix == 2) me->ComputeNormals(wi::scene::MeshComponent::COMPUTE_NORMALS::COMPUTE_NORMALS_HARD);
				if (gg_objpreview_meshfix == 3) me->ComputeNormals(wi::scene::MeshComponent::COMPUTE_NORMALS::COMPUTE_NORMALS_SMOOTH_FAST);
				me->CreateRenderData();
			}
		}
		gg_objpreview_meshfix = 0;
	}
	// Material override on the parked object's subsets, re-applied every submit because the
	// object is reloaded on every fresh hover.
	if ((gg_objpreview_metal >= 0.0f || gg_objpreview_rough >= 0.0f || gg_objpreview_unlit) && s_parkedObject > 0
		&& ObjectExist(s_parkedObject) == 1)
	{
		sObject* pO = GetObjectData(s_parkedObject);
		if (pO && pO->ppMeshList)
		{
			for (int m = 0; m < pO->iMeshCount; ++m)
			{
				sMesh* pM = pO->ppMeshList[m];
				if (!pM) continue;
				wi::scene::MeshComponent* me = scene.meshes.GetComponent(pM->wickedmeshindex);
				if (!me) continue;
				for (size_t si = 0; si < me->subsets.size(); ++si)
				{
					wi::scene::MaterialComponent* ma = scene.materials.GetComponent(me->subsets[si].materialID);
					if (!ma) continue;
					if (gg_objpreview_metal >= 0.0f) ma->metalness = gg_objpreview_metal;
					if (gg_objpreview_rough >= 0.0f) ma->roughness = gg_objpreview_rough;
					if (gg_objpreview_unlit) ma->shaderType = wi::scene::MaterialComponent::SHADERTYPE_UNLIT;
					ma->SetDirty(true);
				}
			}
		}
	}

	s_reqW = width;
	s_reqH = height;
	s_imageId = imageId;
	s_active = true;
}

// Per-frame GPU work. Called from MasterRenderer::Render() AFTER __super::Render(), which is
// where RenderCameraComponents has just recorded the preview camera's own command list - lists
// execute in the order they were begun, so its result is complete by the time ours runs.
void GGObjectPreview_Render(float fExposure)
{
	using namespace GGObjectPreview;
	if (!s_active) return;
	if (s_camEntity == 0) return;

	wi::scene::CameraComponent* cam = wi::scene::GetScene().cameras.GetComponent(s_camEntity);
	if (!cam) return;

	// ⚠ RenderCameraComponents SWAPS rendertarget_render/rendertarget_display at the top of
	// every pass, so these Texture handles move. Read it fresh each frame; caching the handle
	// would alternate between this frame's and last frame's image.
	const wi::graphics::Texture& src = cam->render_to_texture.rendertarget_render;
	if (!src.IsValid()) return;		// first frame after Submit - engine has not allocated yet

	wi::graphics::GraphicsDevice* device = wi::graphics::GetDevice();
	if (!device) return;

	// (re)create the LDR target to match
	if (!s_ldr.IsValid() || s_ldrW != (int)src.desc.width || s_ldrH != (int)src.desc.height)
	{
		wi::graphics::TextureDesc desc;
		desc.width = src.desc.width;
		desc.height = src.desc.height;
		desc.format = wi::graphics::Format::R8G8B8A8_UNORM;
		desc.bind_flags = wi::graphics::BindFlag::SHADER_RESOURCE | wi::graphics::BindFlag::UNORDERED_ACCESS;
		// Postprocess_Tonemap barriers the output back to desc.layout when it finishes, so
		// declaring SHADER_RESOURCE here is what leaves it readable by the ImGui bridge - which
		// draws on a raw ID3D12GraphicsCommandList and issues no barriers of its own.
		desc.layout = wi::graphics::ResourceState::SHADER_RESOURCE;
		desc.mip_levels = 1;
		if (!device->CreateTexture(&desc, nullptr, &s_ldr)) return;
		device->SetName(&s_ldr, "GGMax ObjectPreview LDR");
		s_ldrW = (int)desc.width;
		s_ldrH = (int)desc.height;
		s_imTexId = nullptr;		// force a fresh SRV for the new resource
		s_haveFrame = false;
	}

	if (gg_objpreview_mode < 2) return;   // stage 1: engine render only

	wi::graphics::CommandList cmd = device->BeginCommandList();
	device->EventBegin("GGMax - Object Preview Tonemap", cmd);
	wi::renderer::BindCommonResources(cmd);
	// ★ Both, not one. tonemapCS reads GetCamera() before it does anything else, and an
	// unbound camera CB on a fresh command list is undefined - it hung the device.
	wi::renderer::BindCameraCB(*cam, *cam, *cam, cmd);
	wi::renderer::Postprocess_Tonemap(
		src,
		s_ldr,
		cmd,
		(gg_objpreview_exposure > 0.0f) ? gg_objpreview_exposure : fExposure,
		0.0f,		// brightness
		1.0f,		// contrast
		1.0f,		// saturation
		false,		// dither - the preview is a small still, banding is not the risk here
		nullptr,	// no colour grading LUT
		nullptr,	// no distortion
		nullptr,	// no eye adaption
		nullptr,	// no bloom
		wi::graphics::ColorSpace::SRGB,
		wi::renderer::Tonemap::ACES,
		nullptr,
		1.0f
	);
	device->EventEnd(cmd);

	// hand the result to ImGui. The resource pointer is stable for the life of s_ldr, so the
	// bridge creates its descriptor once and returns the cached handle after that.
	if (gg_objpreview_mode < 3) return;   // stage 2: tonemap but do not show it
	if (s_imTexId == nullptr)
	{
		auto* dx12Device = static_cast<wi::graphics::GraphicsDevice_DX12*>(device);
		if (dx12Device)
		{
			ID3D12Resource* res = dx12Device->GetTextureInternalResource(&s_ldr);
			if (res)
			{
				extern void* ImGui_DX12_BindPreviewTexture(ID3D12Resource * resource, DXGI_FORMAT format);
				s_imTexId = ImGui_DX12_BindPreviewTexture(res, DXGI_FORMAT_R8G8B8A8_UNORM);
			}
		}
	}
	if (s_imTexId != nullptr) s_haveFrame = true;
}

// The one hook into the UI: GetImagePointerView (CImageC_part1.cpp) asks this first, so an
// ImgBtn on the hovered thumbnail draws the live render in place of the static file texture.
// Everything else about the grid cell - size, hover, click, drag - is untouched.
void* GGObjectPreview_GetImageOverride(int iID)
{
	using namespace GGObjectPreview;
	if (!s_active || !s_haveFrame) return nullptr;
	if (iID <= 0 || iID != s_imageId) return nullptr;
	return s_imTexId;
}

// One-line status for the DUMP_OBJPREVIEW harness verb. Names every link in the chain, so a
// blank thumbnail can be told apart from a preview that was never requested (no camera),
// never rendered (engine target invalid), or never bound (no ImGui descriptor).
void GGObjectPreview_DebugStatus(char* buf, int bufsize)
{
	using namespace GGObjectPreview;
	if (!buf || bufsize < 64) return;
	wi::scene::CameraComponent* cam = (s_camEntity != 0) ? wi::scene::GetScene().cameras.GetComponent(s_camEntity) : nullptr;
	const wi::graphics::Texture* src = cam ? &cam->render_to_texture.rendertarget_render : nullptr;
	// What the ENGINE culled for this camera - the line that separates 'the object and
	// lights are not in the pass' from 'they are, and it is just dark'.
	int visObjects = -1, visLights = -1;
	if (cam && cam->render_to_texture.visibility)
	{
		const wi::renderer::Visibility& v = *(const wi::renderer::Visibility*)cam->render_to_texture.visibility.get();
		visObjects = (int)v.visibleObjects.size();
		visLights = (int)v.visibleLights.size();
	}
	extern wi::ecs::Entity g_entityThumbLight, g_entityThumbLight2;
	const wi::scene::LightComponent* tl = g_entityThumbLight ? wi::scene::GetScene().lights.GetComponent(g_entityThumbLight) : nullptr;
	const wi::scene::TransformComponent* tlt = g_entityThumbLight ? wi::scene::GetScene().transforms.GetComponent(g_entityThumbLight) : nullptr;
	// ★ LightComponent::position is the BAKED world position RunLightUpdateSystem writes and
	// the renderer uses. translation_local is only what we asked for.
	float lwx = 0, lwy = 0, lwz = 0, lobjdist = -1.0f;
	if (tl)
	{
		lwx = tl->position.x; lwy = tl->position.y; lwz = tl->position.z;
		if (s_parkedObject > 0 && ObjectExist(s_parkedObject) == 1)
		{
			const float dx = lwx - ObjectPositionX(s_parkedObject);
			const float dy = lwy - ObjectPositionY(s_parkedObject);
			const float dz = lwz - ObjectPositionZ(s_parkedObject);
			lobjdist = sqrtf(dx*dx + dy*dy + dz*dz);
		}
	}
	const wi::scene::WeatherComponent* wx = (wi::scene::GetScene().weathers.GetCount() > 0) ? &wi::scene::GetScene().weathers[0] : nullptr;
	float bdx = 0, bdy = 0, bdz = 0, bddist = -1.0f;
	if (s_backdropObject > 0 && ObjectExist(s_backdropObject) == 1)
	{
		bdx = ObjectPositionX(s_backdropObject);
		bdy = ObjectPositionY(s_backdropObject);
		bdz = ObjectPositionZ(s_backdropObject);
		if (cam)
		{
			const float dx = bdx - cam->Eye.x, dy = bdy - cam->Eye.y, dz = bdz - cam->Eye.z;
			bddist = sqrtf(dx*dx + dy*dy + dz*dz);
		}
	}
	_snprintf(buf, bufsize,
		"camEntity=%llu req=%dx%d imageId=%d parked=%d engineRT=%s(%dx%d) ldr=%s(%dx%d) imTexId=%s haveFrame=%d eye=(%.0f,%.0f,%.0f) visObj=%d visLightCulled=%d litLights=%d mainLights=%d evict=%d exposure=%.3f near=%.1f far=%.0f fov=%.3f backdrop=%d(exist=%d vis=%d img=%d tex=%d at=(%.0f,%.0f,%.0f) dist=%.0f) thumbLight=%llu type=%d int=%.2f range=%.0f local=(%.0f,%.0f,%.0f) world=(%.0f,%.0f,%.0f) distToObj=%.1f col=(%.2f,%.2f,%.2f) ambient=(%.3f,%.3f,%.3f)",
		(unsigned long long)s_camEntity, s_reqW, s_reqH, s_imageId, s_parkedObject,
		(src && src->IsValid()) ? "yes" : "NO",
		(src && src->IsValid()) ? (int)src->desc.width : 0,
		(src && src->IsValid()) ? (int)src->desc.height : 0,
		s_ldr.IsValid() ? "yes" : "NO", s_ldrW, s_ldrH,
		s_imTexId ? "yes" : "NO", s_haveFrame ? 1 : 0,
		cam ? cam->Eye.x : 0.0f, cam ? cam->Eye.y : 0.0f, cam ? cam->Eye.z : 0.0f,
		visObjects, visLights, s_litLights,
		(int)master.masterrenderer.visibility_main.visibleLights.size(), s_evictions,
		(gg_objpreview_exposure > 0.0f) ? gg_objpreview_exposure : master.masterrenderer.getExposure(),
		cam ? cam->zNearP : -1.0f, cam ? cam->zFarP : -1.0f, cam ? cam->fov : -1.0f,
		s_backdropObject,
		(s_backdropObject > 0 && ObjectExist(s_backdropObject) == 1) ? 1 : 0,
		(s_backdropObject > 0 && g_ObjectList[s_backdropObject] && g_ObjectList[s_backdropObject]->bVisible) ? 1 : 0,
		ImageExist(BACKDROPMAGE) ? 1 : 0, s_backdropDiag, bdx, bdy, bdz, bddist,
		(unsigned long long)g_entityThumbLight, tl ? (int)tl->type : -1,
		tl ? tl->intensity : -1.0f, tl ? tl->range : -1.0f,
		tlt ? tlt->translation_local.x : 0.0f, tlt ? tlt->translation_local.y : 0.0f, tlt ? tlt->translation_local.z : 0.0f,
		lwx, lwy, lwz, lobjdist,
		tl ? tl->color.x : -1.0f, tl ? tl->color.y : -1.0f, tl ? tl->color.z : -1.0f,
		wx ? wx->ambient.x : -1.0f, wx ? wx->ambient.y : -1.0f, wx ? wx->ambient.z : -1.0f);
	{
		// 3.97: the level ambient above is what the preview would have inherited; say what it gets.
		const size_t used = strlen(buf);
		if (used + 96 < (size_t)bufsize)
			_snprintf(buf + used, bufsize - used, " studio=%d cube=%d studioFrames=%d key=%.2f amb=%.3f env=%.2f mod=%.3f freeze=%d",
				gg_objpreview_studio, s_studioCubeIndex, s_studioFrames, gg_objpreview_lightint, gg_objpreview_ambient, gg_objpreview_envscale,
				gg_objpreview_modulate, gg_objpreview_freeze);
	}
	buf[bufsize - 1] = 0;
}

// Per-subset material state of whatever the preview currently has parked. Written to a file
// rather than the harness reply because a character is 6-10 subsets and the reply buffer is
// shared. Uses GGDiagFopen so it lands in the diagnostic path, not a stray CWD.
void GGObjectPreview_DumpMaterials(char* result, int resultSize)
{
	using namespace GGObjectPreview;
	const int obj = s_parkedObject;
	if (obj <= 0 || ObjectExist(obj) != 1)
	{
		_snprintf(result, resultSize, "ERROR: no preview object parked (hover a thumbnail first)");
		result[resultSize - 1] = 0;
		return;
	}
	extern FILE* GGDiagFopen(const char* name, const char* mode);
	FILE* f = GGDiagFopen("objpreview_mats.txt", "w");
	if (!f)
	{
		_snprintf(result, resultSize, "ERROR: could not open objpreview_mats.txt");
		result[resultSize - 1] = 0;
		return;
	}
	sObject* pObj = GetObjectData(obj);
	wi::scene::Scene& scene = wi::scene::GetScene();
	int meshes = 0, subsets = 0, blackBase = 0, noBaseTex = 0;
	fprintf(f, "preview object %d  meshCount=%d  visible=%d\n",
		obj, pObj ? pObj->iMeshCount : -1,
		(g_ObjectList[obj] && g_ObjectList[obj]->bVisible) ? 1 : 0);
	static const char* slotName[] = { "BASECOLOR", "NORMAL", "SURFACE", "EMISSIVE",
		"DISPLACEMENT", "OCCLUSION", "TRANSMISSION", "SHEENCOLOR", "SHEENROUGH",
		"CLEARCOAT", "CLEARCOATROUGH", "CLEARCOATNORMAL", "SPECULAR" };
	if (pObj && pObj->ppMeshList)
	{
		for (int m = 0; m < pObj->iMeshCount; ++m)
		{
			sMesh* pMesh = pObj->ppMeshList[m];
			if (!pMesh) { fprintf(f, "  mesh %d: NULL\n", m); continue; }
			meshes++;
			wi::scene::MeshComponent* mesh = scene.meshes.GetComponent(pMesh->wickedmeshindex);
			if (!mesh) { fprintf(f, "  mesh %d: no MeshComponent (wickedmeshindex=%llu)\n",
				m, (unsigned long long)pMesh->wickedmeshindex); continue; }
			// ★ UV coverage per mesh. An empty or degenerate uvset_0 samples one texel of the atlas
			// for the entire mesh - and this atlas is mostly black outside the garment islands.
			// ★ Normal health. A zero-length or absent normal gives N.L == 0 for every light from
			// every direction, which is uniform black that no amount of light can lift - exactly
			// what the torso does while its own texture and material read as perfect.
			float normLenLo = 9e9f, normLenHi = -9e9f;
			int normZero = 0, normNaN = 0;	// 3.98: NaN fails every < and >, so it read as HEALTHY before
			for (size_t ni = 0; ni < mesh->vertex_normals.size(); ++ni)
			{
				const XMFLOAT3& nv = mesh->vertex_normals[ni];
				const float len = sqrtf(nv.x*nv.x + nv.y*nv.y + nv.z*nv.z);
				if (!(len == len)) { normNaN++; continue; }
				if (len < normLenLo) normLenLo = len;
				if (len > normLenHi) normLenHi = len;
				if (len < 0.001f) normZero++;
			}
			float tanLenLo = 9e9f, tanLenHi = -9e9f; int tanZero = 0, tanNaN = 0;
			for (size_t ti = 0; ti < mesh->vertex_tangents.size(); ++ti)
			{
				const XMFLOAT4& tv = mesh->vertex_tangents[ti];
				const float len = sqrtf(tv.x*tv.x + tv.y*tv.y + tv.z*tv.z);
				if (!(len == len)) { tanNaN++; continue; }
				if (len < tanLenLo) tanLenLo = len;
				if (len > tanLenHi) tanLenHi = len;
				if (len < 0.001f) tanZero++;
			}
			float u0lo = 9e9f, u0hi = -9e9f, v0lo = 9e9f, v0hi = -9e9f;
			for (size_t vi = 0; vi < mesh->vertex_uvset_0.size(); ++vi)
			{
				const XMFLOAT2& uv = mesh->vertex_uvset_0[vi];
				if (uv.x < u0lo) u0lo = uv.x;  if (uv.x > u0hi) u0hi = uv.x;
				if (uv.y < v0lo) v0lo = uv.y;  if (uv.y > v0hi) v0hi = uv.y;
			}
			fprintf(f, "  mesh %d: subsets=%d verts=%d uv0=%d uv1=%d colors=%d uv0range=[%.3f..%.3f, %.3f..%.3f]%s\n",
				m, (int)mesh->subsets.size(), (int)mesh->vertex_positions.size(),
				(int)mesh->vertex_uvset_0.size(), (int)mesh->vertex_uvset_1.size(),
				(int)mesh->vertex_colors.size(),
				(u0hi >= u0lo) ? u0lo : 0.0f, (u0hi >= u0lo) ? u0hi : 0.0f,
				(u0hi >= u0lo) ? v0lo : 0.0f, (u0hi >= u0lo) ? v0hi : 0.0f,
				(mesh->vertex_uvset_0.empty() || (u0hi - u0lo) < 0.001f) ? "   <== UV0 EMPTY/DEGENERATE" : "");
			fprintf(f, "          normals=%d len=[%.3f..%.3f] zeroLen=%d NaN=%d tangents=%d%s\n",
				(int)mesh->vertex_normals.size(),
				(normLenHi >= normLenLo) ? normLenLo : 0.0f, (normLenHi >= normLenLo) ? normLenHi : 0.0f,
				normZero, normNaN, (int)mesh->vertex_tangents.size(),
				(mesh->vertex_normals.empty() || normZero > 0 || normNaN > 0) ? "   <== NORMALS MISSING/ZERO/NaN" : "");
			fprintf(f, "          tangents len=[%.3f..%.3f] zeroLen=%d nan=%d%s\n",
				(tanLenHi >= tanLenLo) ? tanLenLo : 0.0f, (tanLenHi >= tanLenLo) ? tanLenHi : 0.0f,
				tanZero, tanNaN,
				(mesh->vertex_tangents.empty() || tanZero > 0 || tanNaN > 0) ? "   <== TANGENT FRAME DEGENERATE" : "");
			// 3.98: skinning facts. A skinned mesh draws its SKINNED normals (so_nor), accumulated in
			// half precision in skinningCS - a tiny bone scale underflows the normal to zero while the
			// float position survives. Weights, bone scales and a per-vertex table say which.
			{
				int noWeight = 0; float wmin = 9e9f, wmax = -9e9f;
				for (size_t wi2 = 0; wi2 < mesh->vertex_boneweights.size(); ++wi2)
				{
					const XMFLOAT4& w4 = mesh->vertex_boneweights[wi2];
					const float ws = w4.x + w4.y + w4.z + w4.w;
					if (ws < 0.01f) noWeight++;
					if (ws < wmin) wmin = ws; if (ws > wmax) wmax = ws;
				}
				fprintf(f, "          SKINNING: armatureID=%llu boneidx=%d boneweights=%d weightSum=[%.3f..%.3f] noWeight=%d so_pos=%d so_nor=%d so_tan=%d\n",
					(unsigned long long)mesh->armatureID, (int)mesh->vertex_boneindices.size(), (int)mesh->vertex_boneweights.size(),
					mesh->vertex_boneweights.empty() ? 0.0f : wmin, mesh->vertex_boneweights.empty() ? 0.0f : wmax, noWeight,
					mesh->so_pos.IsValid() ? 1 : 0, mesh->so_nor.IsValid() ? 1 : 0, mesh->so_tan.IsValid() ? 1 : 0);
				const wi::scene::ArmatureComponent* arm = (mesh->armatureID != wi::ecs::INVALID_ENTITY) ? scene.armatures.GetComponent(mesh->armatureID) : nullptr;
				if (arm)
				{
					fprintf(f, "          armature: bones=%d boneData=%d\n", (int)arm->boneCollection.size(), (int)arm->boneData.size());
					for (size_t bi = 0; bi < arm->boneData.size() && bi < 16; ++bi)
					{
						const ShaderTransform& st = arm->boneData[bi];
						// rows of the 3x4: column lengths of the 3x3 are the bone's scale
						const float sx = sqrtf(st.mat0.x*st.mat0.x + st.mat1.x*st.mat1.x + st.mat2.x*st.mat2.x);
						const float sy = sqrtf(st.mat0.y*st.mat0.y + st.mat1.y*st.mat1.y + st.mat2.y*st.mat2.y);
						const float sz = sqrtf(st.mat0.z*st.mat0.z + st.mat1.z*st.mat1.z + st.mat2.z*st.mat2.z);
						const wi::scene::NameComponent* bn = (bi < arm->boneCollection.size()) ? scene.names.GetComponent(arm->boneCollection[bi]) : nullptr;
						fprintf(f, "            bone %d '%s' scale=(%.6g, %.6g, %.6g)%s\n", (int)bi, bn ? bn->name.c_str() : "?", sx, sy, sz,
							(sx < 1e-3f || sy < 1e-3f || sz < 1e-3f) ? "   <== TINY: half-precision normal skinning underflows" : "");
					}
				}
				if (mesh->vertex_positions.size() <= 300)
				{
					for (size_t vi = 0; vi < mesh->vertex_positions.size(); ++vi)
					{
						const XMFLOAT3 p3 = mesh->vertex_positions[vi];
						const XMFLOAT3 n3 = (vi < mesh->vertex_normals.size()) ? mesh->vertex_normals[vi] : XMFLOAT3(0, 0, 0);
						const XMFLOAT2 uv = (vi < mesh->vertex_uvset_0.size()) ? mesh->vertex_uvset_0[vi] : XMFLOAT2(0, 0);
						const XMUINT4 bi4 = (vi < mesh->vertex_boneindices.size()) ? mesh->vertex_boneindices[vi] : XMUINT4(0, 0, 0, 0);
						const XMFLOAT4 bw4 = (vi < mesh->vertex_boneweights.size()) ? mesh->vertex_boneweights[vi] : XMFLOAT4(0, 0, 0, 0);
						fprintf(f, "            v%3d pos=(%.3f,%.3f,%.3f) nor=(%.3f,%.3f,%.3f) uv=(%.3f,%.3f) bones=(%u,%u,%u,%u) w=(%.2f,%.2f,%.2f,%.2f)\n",
							(int)vi, p3.x, p3.y, p3.z, n3.x, n3.y, n3.z, uv.x, uv.y, bi4.x, bi4.y, bi4.z, bi4.w, bw4.x, bw4.y, bw4.z, bw4.w);
					}
				}
			}
			for (size_t si = 0; si < mesh->subsets.size(); ++si)
			{
				subsets++;
				wi::scene::MaterialComponent* mat = scene.materials.GetComponent(mesh->subsets[si].materialID);
				if (!mat) { fprintf(f, "    subset %d: NO MATERIAL\n", (int)si); continue; }
				const wi::scene::NameComponent* nm = scene.names.GetComponent(mesh->subsets[si].materialID);
				const XMFLOAT4 bc = mat->baseColor;
				const bool bBlack = (bc.x + bc.y + bc.z) < 0.02f;
				if (bBlack) blackBase++;
				fprintf(f, "    subset %d  '%s'\n", (int)si, nm ? nm->name.c_str() : "?");
				fprintf(f, "      shaderType=%d blend=%d alphaRef=%.3f baseColor=(%.3f,%.3f,%.3f,%.3f)%s\n",
					(int)mat->shaderType, (int)mat->userBlendMode, mat->alphaRef,
					bc.x, bc.y, bc.z, bc.w, bBlack ? "   <== BLACK BASE COLOUR" : "");
				fprintf(f, "      emissive=(%.3f,%.3f,%.3f,%.3f) metal=%.2f rough=%.2f reflect=%.2f\n",
					mat->emissiveColor.x, mat->emissiveColor.y, mat->emissiveColor.z, mat->emissiveColor.w,
					mat->metalness, mat->roughness, mat->reflectance);
				for (int t2 = 0; t2 < wi::scene::MaterialComponent::TEXTURESLOT_COUNT; ++t2)
				{
					const auto& tex = mat->textures[t2];
					if (!tex.resource.IsValid() && tex.name.empty()) continue;
					const bool bValid = tex.resource.IsValid();
					if (t2 == wi::scene::MaterialComponent::BASECOLORMAP && !bValid) noBaseTex++;
					fprintf(f, "      slot%-2d %-15s %-8s uvset=%d '%s'\n", t2,
						(t2 < 13) ? slotName[t2] : "?",
						bValid ? "RESIDENT" : "ABSENT", (int)tex.uvset, tex.name.c_str());
				}
			}
		}
	}
	// 3.98: every object the PREVIEW camera's own visibility pass kept. Subject + backdrop is 2;
	// visObj has read 7..12 since 3.84, and anything else sitting at the park point renders INSIDE
	// or around the subject. Name, mesh, world AABB centre/size and the material's shader type.
	{
		wi::scene::CameraComponent* pcam = (s_camEntity != 0) ? scene.cameras.GetComponent(s_camEntity) : nullptr;
		if (pcam && pcam->render_to_texture.visibility)
		{
			const wi::renderer::Visibility& vis = *(const wi::renderer::Visibility*)pcam->render_to_texture.visibility.get();
			fprintf(f, "\nPREVIEW CAMERA SEES %d objects:\n", (int)vis.visibleObjects.size());
			for (size_t vi = 0; vi < vis.visibleObjects.size(); ++vi)
			{
				const uint32_t oi = vis.visibleObjects[vi];
				if (oi >= scene.objects.GetCount()) continue;
				const wi::ecs::Entity oe = scene.objects.GetEntity(oi);
				const wi::scene::ObjectComponent& oc = scene.objects[oi];
				const wi::scene::NameComponent* on = scene.names.GetComponent(oe);
				const wi::scene::NameComponent* mn = scene.names.GetComponent(oc.meshID);
				const wi::primitive::AABB& ab = scene.aabb_objects[oi];
				const XMFLOAT3 c = ab.getCenter(), h = ab.getHalfWidth();
				const wi::scene::MeshComponent* om = scene.meshes.GetComponent(oc.meshID);
				int st = -1;
				if (om && !om->subsets.empty()) { const wi::scene::MaterialComponent* omat = scene.materials.GetComponent(om->subsets[0].materialID); if (omat) st = (int)omat->shaderType; }
				fprintf(f, "  [%d] ent=%llu obj='%s' mesh='%s' centre=(%.0f,%.0f,%.0f) half=(%.1f,%.1f,%.1f) verts=%d shader=%d\n",
					(int)vi, (unsigned long long)oe, on ? on->name.c_str() : "?", mn ? mn->name.c_str() : "?",
					c.x, c.y, c.z, h.x, h.y, h.z, om ? (int)om->vertex_positions.size() : -1, st);
			}
		}
	}
	fclose(f);
	_snprintf(result, resultSize,
		"OK: DUMP_OBJPREVIEW_MATS obj=%d meshes=%d subsets=%d blackBaseColour=%d missingBaseTex=%d -> objpreview_mats.txt",
		obj, meshes, subsets, blackBase, noBaseTex);
	result[resultSize - 1] = 0;
}
